# Change these first
owner: InfoSecREDD # Your GitHub organization or username, where this repository lives
repo: Uptime-Monitor # The name of this repository

sites:
  - name: Cloud
    url: $CLOUD_URL
    headers:
      - "$CF_ID"
      - "$CF_SECRET"
  - name: GitLab
    url: $GITLAB_URL
#  - name: IPv6 test
#    url: forwardemail.net
#    port: 80
#    check: "tcp-ping"
#    ipv6: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: monitor.serverbackend.net
  # baseUrl: /Uptime-Monitor
  logoUrl: https://raw.githubusercontent.com/InfoSecREDD/Uptime-Monitor/refs/heads/master/assets/7-hydroxymitragynine-molecule.svg
  name: Uptime Monitor
  introTitle: "**Uptime Monitor Tool**"
  introMessage: Data is refreshed every **5 minutes**.
  navbar:
    - title: Status
      href: /
i18n:
  footer: Powered by Wizards
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
